# Generated by Django 2.2 on 2020-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('news_summary', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('news_time', models.CharField(max_length=10, verbose_name='新闻标题')),
            ],
            options={
                'verbose_name': '新闻栏',
                'verbose_name_plural': '新闻栏',
                'db_table': 'news',
            },
        ),
    ]
