# Generated by Django 2.2 on 2020-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_summary',
            field=models.CharField(max_length=255, verbose_name='新闻概述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_time',
            field=models.CharField(max_length=10, verbose_name='新闻时间'),
        ),
    ]
