# Generated by Django 2.2 on 2020-03-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_auto_20200315_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_detail',
            field=models.TextField(default=1, verbose_name='新闻内容'),
            preserve_default=False,
        ),
    ]
