# Generated by Django 2.2 on 2020-03-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_news_news_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=100, verbose_name='新闻标题'),
        ),
    ]
