# Generated by Django 2.2 on 2020-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_auto_20200316_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_detail', models.CharField(max_length=30, verbose_name='公告内容')),
                ('announcement_time', models.CharField(max_length=10, verbose_name='公告时间')),
            ],
            options={
                'verbose_name': '公告栏',
                'verbose_name_plural': '公告栏',
                'ordering': ('-announcement_time',),
            },
        ),
    ]
