# Generated by Django 2.2 on 2020-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_auto_20200409_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_time',
            field=models.DateField(auto_now=True, verbose_name='公告时间'),
        ),
    ]
