# Generated by Django 2.2 on 2020-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_auto_20200409_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-id',), 'verbose_name': '公告栏', 'verbose_name_plural': '公告栏'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_time',
            field=models.DateField(auto_now_add=True, verbose_name='公告时间'),
        ),
    ]
