# Generated by Django 2.2 on 2020-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppletRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNumber', models.CharField(help_text='格式：1.0.0', max_length=5, verbose_name='版本号')),
                ('updateInformation', models.TextField(verbose_name='更新信息')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '程序版本信息',
                'verbose_name_plural': '程序版本信息',
                'ordering': ('-updateTime',),
            },
        ),
    ]
