# Generated by Django 2.2 on 2020-04-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationModule', '0007_auto_20200331_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackinfo',
            name='feedbackContact',
            field=models.CharField(default=1, max_length=15, verbose_name='QQ/邮箱(选填)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costinfo',
            name='costTitle',
            field=models.CharField(max_length=20, verbose_name='费用'),
        ),
    ]
