# Generated by Django 2.2 on 2020-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationModule', '0008_auto_20200402_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackinfo',
            name='feedbackContact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ/邮箱(选填)'),
        ),
    ]
