# Generated by Django 2.2 on 2020-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationModule', '0009_auto_20200402_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairinfo',
            name='repairContent',
        ),
        migrations.AddField(
            model_name='repairinfo',
            name='repairNote',
            field=models.TextField(default=1, verbose_name='报修备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairinfo',
            name='repairPhone',
            field=models.CharField(default=1, max_length=11, verbose_name='联系电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repairinfo',
            name='repairTitle',
            field=models.CharField(max_length=20, verbose_name='报修标题'),
        ),
    ]
