# Generated by Django 2.2 on 2020-04-04 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InformationModule', '0010_auto_20200404_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.TextField(verbose_name='留言内容')),
                ('messageNickname', models.CharField(max_length=10, verbose_name='留言昵称')),
                ('messageTime', models.DateTimeField(auto_now=True, verbose_name='留言时间')),
                ('messageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言人')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
            },
        ),
    ]
