# Generated by Django 2.2 on 2020-04-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformationModule', '0011_messageboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageboard',
            options={'ordering': ('-messageTime',), 'verbose_name': '留言板', 'verbose_name_plural': '留言板'},
        ),
    ]
