# Generated by Django 2.2.5 on 2020-02-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPersonnel', '0002_auto_20200202_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
