# Generated by Django 2.2 on 2020-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPersonnel', '0004_auto_20200406_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
