# Generated by Django 2.2 on 2020-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPersonnel', '0006_auto_20200406_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unitType',
            field=models.IntegerField(choices=[(1, '140m²'), (2, '120m²'), (3, '100m²')], default=1, verbose_name='户型'),
            preserve_default=False,
        ),
    ]
